general number of classes for service
andreyDelay/bookService pull request #1
Opened 2023-05-30 14:46 UTC by andreyDelay

Добавил пока основное, тестировал постменом пока что, создал несколько запросов там.

2023-05-30 15:14 UTC, kegisa requested changes

2023-05-30 15:14 UTC, kegisa commented on src/main/java/andrey/library/books/exception/ApiExceptionHandlerController.java
> +    @ExceptionHandler({BookNotFoundException.class})
здесь не ApiException должен быть?

2023-05-30 15:14 UTC, kegisa commented on src/main/java/andrey/library/books/mapper/MapStructAuthorMapper.java
> +    MapStructAuthorMapper MAPPER = Mappers.getMapper(MapStructAuthorMapper.class);
А для чего это?

2023-05-30 15:14 UTC, kegisa commented on src/main/java/andrey/library/books/mapper/MapStructBookMapper.java
> +    @Mapping(source = "authors", target = "authors") //Check if working without this
это можн убрать, если названия одинаковые все будет ок

2023-05-30 15:14 UTC, kegisa commented on src/main/java/andrey/library/books/model/Author.java
> +}
а toString норм отрабатывает и hashCOde?

2023-05-30 15:14 UTC, kegisa commented on src/main/java/andrey/library/books/service/BookServiceImpl.java
> +        return Optional.ofNullable(MAPPER.fromBook(bookToSave))
давай mapper как бин юзать

2023-05-30 15:14 UTC, kegisa commented on src/main/java/andrey/library/books/service/BookServiceImpl.java
> +public class BookServiceImpl implements BookService {
здесь лучше повесить transactional с readonly true

2023-05-30 15:14 UTC, kegisa commented on src/main/java/andrey/library/books/service/BookServiceImpl.java
> +    //Без @Transactional падало с ошибкой No EntityManager with actual transaction available for current thread -
в краде вроде только на стандартных уже есть transaction с параметром [MANDATORY]. Возожно по умолчнию будет только [REQUIRED]

2023-05-30 15:14 UTC, kegisa commented on src/main/resources/db/changelog/init/db.changelog-create-book_authors-table.yml
> +            onDelete: CASCADE
вот это опасная штука, но в рамках пет прожекта ок

2023-06-01 13:19 UTC, andreyDelay commented on src/main/java/andrey/library/books/model/Author.java
> +}
Исправил аннотацией @ToString.Exclude над дочерней сущностью

2023-06-01 13:19 UTC, andreyDelay commented on src/main/java/andrey/library/books/service/BookServiceImpl.java
> +public class BookServiceImpl implements BookService {
Добавил над классом, оставил над методами (без явной пометки "readOnly = false")

2023-06-01 13:21 UTC, andreyDelay commented on src/main/resources/db/changelog/init/db.changelog-create-book_authors-table.yml
> +            onDelete: CASCADE
Тут я пока что на теории, но до конца не понимаю что лучше. 
Удалив книги(у) оставлять "подвисших" авторов никому не принадлежащих?
Сценариев , конечно, может быть много наверняка, но пока не понял всей картины для себя)

2023-06-07 14:12 UTC, kegisa requested changes

2023-06-07 14:12 UTC, kegisa commented on src/main/java/andrey/library/books/repository/AuthorRepository.java
> +    Author findByFirstNameAndLastName(String firstName, String lastName);
может здесь optional сделать?

2023-06-07 14:12 UTC, kegisa commented on src/main/java/andrey/library/books/service/BookServiceImpl.java
> +        booksRepository.deleteByTitle(title);
здесь если не бюуедт такой книги в бд что словим?

2023-06-08 13:33 UTC, kegisa approved these changes

2023-06-08 13:46 UTC, merged